name: Deploy
on: 
  workflow_call:
    inputs:
      exec-files:
        description: name of the execution file
        type: string
        required: true
        default: dist
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.exec-files }}