name: Deploy
on: 
  workflow_call:
    inputs:
      exec-files:
        description: name of the execution file
        type: string
        required: true
        default: dist
    outputs:
      result:
        description: deploy result
        value: ${{ jobs.deploy.outputs.result }}
jobs:
  deploy:
    outputs:
      result: ${{ steps.output.result }}
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.exec-files }}
      - name: Set output
        id: output
        if: success()
        run: echo "::set-output -name result::success"